/*
 * This source file was generated by the Gradle 'init' task
 */
package app;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class AppTest {
    private  TicTacToeGame game = new TicTacToeGame();

    @BeforeEach
void setUp() {
    game = new TicTacToeGame();
}
    @Test 
    public void setGrid() {
        game.setGrid(new char[][]{
            { ' ', ' ', ' ' },
            { ' ', ' ', ' ' },
            { ' ', ' ', ' ' },
        });
        assertArrayEquals(game.getGrid(),new char[][]{
                    { ' ', ' ', ' ' },
                    { ' ', ' ', ' ' },
                    { ' ', ' ', ' ' },
                });
        
            }
    @Test
    public void setCurrentPlayer() {
        game.setCurrentPlayer('X');
        assertEquals('X',game.getCurrentPlayer());
    }

    @Test
    public void setWinner() {
        game.setWinner('O');
        assertEquals('O',game.getWinner());
    }

    @Test
    public void TestProcessMove() {
        
        char [][] grid = game.getGrid();
       game.processMove(0,0);
       
      //assertEquals('X',game.getGrid()[0][0]);
     
       assertEquals('O',game.getCurrentPlayer());
       game.processMove(1, 0);
      
       game.processMove(0, 1);
       game.processMove(1, 1);
       game.processMove(0, 2);
       assertEquals('X',game.getWinner());  
    }
}

